name = "DateFormats"
uuid = "44557152-fe0a-4de1-8405-416d90313ce6"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.17"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[weakdeps]
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"

[extensions]
InverseFunctionsExt = "InverseFunctions"

[compat]
InverseFunctions = "0.1.7"
julia = "1.5"

[extras]
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
