name = "DateFormats"
uuid = "44557152-fe0a-4de1-8405-416d90313ce6"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.16"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"

[compat]
DocStringExtensions = "0.8.3, 0.9"
InverseFunctions = "0.1.7"
julia = "1.5"
