name = "DateFormats"
uuid = "44557152-fe0a-4de1-8405-416d90313ce6"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.11"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
DocStringExtensions = "0.8"
julia = "1.5"
